import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider"
import React from "react";
import {SessionWrapper} from "@/components/my-ui/session-wrapper";
import '@fontsource/dancing-script'; // Import the Dancing Script font
import '@fontsource/lexend';
import {Box} from "@chakra-ui/react";
import {Toaster} from "@/components/ui/toaster"; // Import Lexend font

export const metadata: Metadata = {
  title: "English Practice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body >
        <Provider>
          <SessionWrapper>
              {children}
          </SessionWrapper>
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
