import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider"
import React from "react";


export const metadata: Metadata = {
  title: "English Practice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
