name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/english-master:latest
          build-args: |
            KEYCLOAK_ID=${{ secrets.KEYCLOAK_ID }}
            KEYCLOAK_SECRET=${{ secrets.KEYCLOAK_SECRET }}
            KEYCLOAK_ISSUER=${{ secrets.KEYCLOAK_ISSUER }}
            NEXT_PUBLIC_KEYCLOAK_ID=${{ secrets.NEXT_PUBLIC_KEYCLOAK_ID }}
            NEXT_PUBLIC_KEYCLOAK_LOGOUT_URL=${{ secrets.NEXT_PUBLIC_KEYCLOAK_LOGOUT_URL }}
            NEXT_PUBLIC_READING_SERVICE_URL=${{ secrets.NEXT_PUBLIC_READING_SERVICE_URL }}
            NEXT_PUBLIC_LISTENING_SERVICE_URL=${{ secrets.NEXT_PUBLIC_LISTENING_SERVICE_URL }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # Step 1: Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 2: Deploy to Azure Container App
      - name: Deploy to Azure Container App
        run: |
          RESOURCE_GROUP=${{secrets.AZURE_RESOURCE_GROUP}}
          CONTAINER_APP_NAME="english-master-noideatt-app"
          LOCATION="southeastasia"
          
          # Deploy the Docker image to Azure Container App
          az containerapp create \
            --name $CONTAINER_APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --image ${{ secrets.DOCKER_USERNAME }}/english-master:latest \
            --cpu 0.5 --memory 1Gi \
            --environment ${{secrets.AZURE_CONTAINERAPPS_ENVIRONMENT}} \
            --min-replicas 0 \
            --max-replicas 1 \
            --ingress external \
            --target-port 3000 
